stages:
  split:
    cmd: python src/split.py data/bank.csv data/prepared
    deps:
      - src/split.py
      - data/bank.csv
    params:
      - split
    outs:
      - data/prepared/train.csv
      - data/prepared/test.csv

  train:
    cmd: python src/train.py data/prepared/train.csv models/model.joblib
    deps:
      - src/train.py
      - data/prepared/train.csv
    params:
      - train
    outs:
      - models/model.joblib

  evaluate:
    cmd: python src/evaluate.py models/model.joblib data/prepared/test.csv metrics/metrics.json
    deps:
      - src/evaluate.py
      - models/model.joblib
      - data/prepared/test.csv
    metrics:
      - metrics/metrics.json:
          cache: false